---
- name: Install Python 3
  apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-wheel
    state: latest
  tags:
    - pretalx

- name: Install other dependencies
  apt:
    name:
      - gcc
      - gettext
      - git
      - redis-server
      - sqlite3
    state: present
  tags:
    - pretalx
