---
- name: Install Python 3
  apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-wheel
    state: present
  tags:
    - pretalx

- name: Install other dependencies
  apt:
    name:
      - gcc
      - gettext
      - git
    state: present
  tags:
    - pretalx

- name: Install sqlite
  apt:
    name:
      - sqlite3
    state: present
  when: pretalx_database_backend != 'postgresql' and pretalx_database_backend != 'mysql'
  tags:
    - pretalx

- name: Install redis
  apt:
    name:
      - redis-server
    state: present
  when: pretalx_redis
  tags:
    - pretalx
